theme: jekyll-theme-slate
title: "Ben Huenemann"
description: <a href=mailto:"bhuenemann3@nebraska.edu">bhuenemann3@nebraska.edu</a>
logo: https://raw.githubusercontent.com/bhuenemann/bhuenemann.github.io/main/documents/Profile.jpeg
